/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;
import io.javalin.Javalin;

public class App {

    private static int getPort() {
        String port = System.getenv().getOrDefault("PORT", "5000");
        return Integer.valueOf(port);
    }


    public static Javalin getApp() {
        Javalin app = Javalin.create(config -> {
            config.enableDevLogging(); // enable extensive development logging for http and websocket
        });
        return app;
    }

    public static void main(String[] args) {
        Javalin app = getApp();
        app.start(getPort());
        app.get("/", ctx -> ctx.result("Hello World"));
    }
}
